// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_zom_zombie_slackjaw_head";
	a[1] = "c_zom_zombie_mask_head";
	a[2] = "c_zom_zombie_hellcatraz_head";
	a[3] = "c_zom_zombie_barbwire_head";
	return a;
}
