// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_zom_dlc0_zom_head1";
	a[1] = "c_zom_dlc0_zom_head1_blueeyes";
	a[2] = "c_zom_dlc0_zom_head2";
	a[3] = "c_zom_dlc0_zom_head2_blueeyes";
	a[4] = "c_zom_dlc0_zom_head3";
	a[5] = "c_zom_dlc0_zom_head3_blueeyes";
	a[6] = "c_zom_dlc0_zom_head4";
	a[7] = "c_zom_dlc0_zom_head4_blueeyes";
	return a;
}
