// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_zom_dlc0_zom_solciv_body1");
	self.headModel = codescripts\character::randomElement(xmodelalias\c_zom_heads_alias::main());
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
	self.torsoDmg1 = "c_zom_dlc0_zom_solciv_body1_upclean";
	self.torsoDmg2 = "c_zom_dlc0_zom_solciv_body1_rarmoff";
	self.torsoDmg3 = "c_zom_dlc0_zom_solciv_body1_larmoff";
	self.torsoDmg5 = "c_zom_dlc0_zom_solciv_body1_behead";
	self.legDmg1 = "c_zom_dlc0_zom_solciv_body1_lowclean";
	self.legDmg2 = "c_zom_dlc0_zom_solciv_body1_rlegoff";
	self.legDmg3 = "c_zom_dlc0_zom_solciv_body1_llegoff";
	self.legDmg4 = "c_zom_dlc0_zom_solciv_body1_legsoff";
	self.gibSpawn1 = "c_zom_dlc0_zom_haz_body1_g_rarmspawn";
	self.gibSpawnTag1 = "J_Elbow_RI";
	self.gibSpawn2 = "c_zom_dlc0_zom_solciv_body1_g_larmspawn";
	self.gibSpawnTag2 = "J_Elbow_LE";
	self.gibSpawn3 = "c_zom_dlc0_zom_solciv_body1_g_rlegspawn";
	self.gibSpawnTag3 = "J_Knee_RI";
	self.gibSpawn4 = "c_zom_dlc0_zom_solciv_body1_g_llegspawn";
	self.gibSpawnTag4 = "J_Knee_LE";
}

precache()
{
	precacheModel("c_zom_dlc0_zom_solciv_body1");
	codescripts\character::precacheModelArray(xmodelalias\c_zom_heads_alias::main());
	precacheModel("c_zom_dlc0_zom_solciv_body1_upclean");
	precacheModel("c_zom_dlc0_zom_solciv_body1_rarmoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_larmoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_behead");
	precacheModel("c_zom_dlc0_zom_solciv_body1_lowclean");
	precacheModel("c_zom_dlc0_zom_solciv_body1_rlegoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_llegoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_legsoff");
	precacheModel("c_zom_dlc0_zom_haz_body1_g_rarmspawn");
	precacheModel("c_zom_dlc0_zom_solciv_body1_g_larmspawn");
	precacheModel("c_zom_dlc0_zom_solciv_body1_g_rlegspawn");
	precacheModel("c_zom_dlc0_zom_solciv_body1_g_llegspawn");
	precacheModel("c_zom_dlc0_zom_solciv_body1_upclean");
	precacheModel("c_zom_dlc0_zom_solciv_body1_rarmoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_larmoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_behead");
	precacheModel("c_zom_dlc0_zom_solciv_body1_lowclean");
	precacheModel("c_zom_dlc0_zom_solciv_body1_rlegoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_llegoff");
	precacheModel("c_zom_dlc0_zom_solciv_body1_legsoff");
	precacheModel("c_zom_dlc0_zom_haz_body1_g_rarmspawn");
	precacheModel("c_zom_dlc0_zom_solciv_body1_g_larmspawn");
	precacheModel("c_zom_dlc0_zom_solciv_body1_g_rlegspawn");
	precacheModel("c_zom_dlc0_zom_solciv_body1_g_llegspawn");
}
